### ISSUE TITLE
Feature to copy emoji to clipboard 

### ISSUE THREAD

**Issue by aswinikalyan30** [aditya-singh9/kekfinder#20]
Upon receiving the results, user can copy the emoji onto their clipboard to use it elsewhere

**Comment by aditya-singh9** [comment]
I guess user can copy the emojis. When user clicks on the emoji that specific emoji gets copied in your clipboard and  there is a message saying "Copied" on the emoji box.

If there is an issue with the copying can you please elaborate in comments and solve the issue. I will assign it to you.

**Comment by aswinikalyan30** [comment]
oh okay!
