### ISSUE TITLE
When nothing is searched, show emojis.

### ISSUE THREAD

**Issue by heysouravv** [aditya-singh9/kekfinder#21]

**Comment by aditya-singh9** [comment]
Can you please elaborate the issue

**Comment by KaifKhan7393** [comment]
It is good if we add some animation on emoji card when we hover it like scaling the card size

**Comment by Substancia** [comment]
Is this still available? Else I am interested.

**Comment by aditya-singh9** [comment]
I think he is not available.
I am assiging it to you.

Can you please elaborate a little about what you intend to add or change.

**Comment by Substancia** [comment]
Yes, but beforehand, do we have a discord/slack server for communication? I might have a handful of suggestions ranging outside this issue, like say code structure. These are mere suggestions btw, I can live without these too.

**Comment by aditya-singh9** [comment]
Yes i have my discord id  "Sean wood#6410"
You can reach out to me here.

**Comment by Rudresh-pandey** [comment]
**Hi, i have some idea's :**

1. Adding Shadow color (#ffc83d) same as the light theme toggle button :-
![image](https://user-images.githubusercontent.com/96531798/193384147-fa386823-b0f6-46be-b8c4-2e6c6ecf03fd.png)

2. changing the scroll-bar / scroll-bar thumb :-
  **Light- theme :**
![image](https://user-images.githubusercontent.com/96531798/193384316-32b05f51-9476-481d-99e4-5f410aa507b1.png)

  **Dark- theme :**
![image](https://user-images.githubusercontent.com/96531798/193384341-eb71ec45-cfc3-45cf-813c-12de6cf380d0.png)

### **And some more , which i am designing in figma and adobe xd, then testing in the code**

**Comment by Substancia** [comment]
I would suggest that when there's no search phrase in the search field, instead of leaving the emoji results field empty, we could have a "recent emojis" list but with a weighted distribution regarding how often an emoji is searched for?

Also wasn't this issue assigned to me earlier? Why the change in assignee?

**Comment by aditya-singh9** [comment]
Yeah, i think @Substancia idea is more appealing and as earlier, he asked me to assign it to him. I think i should remove @Rudresh-pandey as assignee and put @Substancia there.

@Rudresh-pandey you can add something new and open an issue about it.

**Comment by aditya-singh9** [comment]
@Rudresh-pandey i have opened a new issue about you adding new emojis and shadow stuff, please respond in that thread with a confirmation so that i can assign it to you.

**Comment by Substancia** [comment]
This enhancement would also cover the feature to be in dark mode as well (maybe except for some dark theme styling mismatches, which we can discuss if and when it arises). Will raise a PR soon.

On a different note, I'm new to contributing to massively contributed open-source projects like in Hacktoberfest (so please bare with me). I saw somewhere that I'll need to fork the repo and work instead of making a branch in original repo, but is this extra step of indirection important here? (Sorry I don't know if that will cause issues, and it's fine by me however way we're moving)

**Comment by aditya-singh9** [comment]
Creating a fork is best practises the maintainer can track the progress too

I would suggest you to make a fork and then do the changes and then create a pr.

**Comment by Substancia** [comment]
@aditya-singh9 I have implemented a recent emojis suggestion when the search bar is empty. Changes are currently in my forked repo branch https://github.com/Substancia/kekfinder/commit/fa77b8666ea48c65521423f2678c091ad97b71c0. Please take a look and let me know of any changes needed.

As for the "weighted recents" idea, where more frequently searched emojis appear higher in the list, it's not implemented yet (now the last used emoji will be at top). I'd like to know what sort of weighted mechanism you'd prefer for that, if we're doing that.

Cheers!

**Comment by aditya-singh9** [comment]
I guess we can make two rows 
In the 1st row there can be the emojis which are frequently copied or searched.

In the 2nd row there can be the emojis which are recently searched or copied

We do not need to label the rows ase recent or frequent, that would be irrelevant.


We can discuss the order of rows (which row comes first) later.

You can give suggestions to the order by providing some reasoning.

You can also give suggestions about this whole feature.

**Comment by Substancia** [comment]
I'm not sure how "recently searched" emojis row can work, since we search just the keywords and each keyword maps to multiple emojis (eg.: searching "fir" gives us emojis of fire and firetrucks etc.). Once I get a clearer idea, I can implement it. Can you give a bit more details?

P.S.: I forgot to ask earlier, when search bar is empty, the max number of suggested emojis is currently set to 4 (in the code it is set with a variable "RECENTSLIMIT" in item.js file). What would you suggest as a good number? You can always change it easily in the future by editing the var value.

**Comment by aditya-singh9** [comment]
Instead of recent searched can you do it for recent used? Or frequently used

Iguess we should do only one, you can choose between recent used and frequently used, its upto you

I am also giving you the freedom of selecting the max number of suggested emojis.

**Comment by Substancia** [comment]
Alright, the current branch mentioned above has "recently used" list, and I'll do a research on good weighted methods for implementing "frequently used", will update you with my success/failure by tomorrow morning.

As for the max number of suggestions, I think 10 would be a good number, so going with that.

**Comment by Substancia** [comment]
Weights have been implemented to frequently searched emojis in recent suggestions, https://github.com/Substancia/kekfinder/commit/e446f60d7711c8292f074be3351f6e946909d814

Basically every time an emoji is clicked, a weight of 5 is added to it, while all other emojis in recents list reduces weight by 1 (until it settles at weight 0, no lower). This way more frequently used emojis stay at top of recent suggestions list. Necessary comments added in code's logic.

Way to test:-
1. Search for "star" and click on one (now weight of star is 5)
2. Search for "fire" and click on it (now fire weighs 5, star weighs 4, so fire appears first)
3. Click on star again (now fire weighs 4, star weighs 4 + 5 = 9, so star appears first)

4. Click on star again (star weighs 14 now, fire weighs 3, so star appears first)
5. Click on fire (star weighs 13, fire now weighs 3 + 5 = 8, lower than star's weight, so star first again)

This testing logic could sound a bit complicated, but if you freely use it, you can see the impact of frequently used emojis.

Let me know of any required changes or questions, and once you're good with the feature, I'll raise a PR.

**Comment by aditya-singh9** [comment]
It isnt complicated and i appreciate your work

I am totally good with it

I think this pr and the pr with search bar stickness and some ui fixes has done some good to this project.
You can create a pr.
Thanks

**Comment by aditya-singh9** [comment]
Hey
Can you please look into https://github.com/aditya-singh9/kekfinder/issues/46
And code the project accordingly

I kinda like this ui

Thanks

**Comment by Substancia** [comment]
I'll sync the fork once and create a PR right away. As for [#46](https://github.com/aditya-singh9/kekfinder/issues/21#:~:text=please%20look%20into-,%2346,-And%20code%20the), I see it has already been assigned to someone. Let me know if you want me to take it up.
