### ISSUE TITLE
It is good if we add some animation on emoji card when we hover it like scaling the card size

### ISSUE THREAD

**Issue by aditya-singh9** [aditya-singh9/kekfinder#23]
It is good if we add some animation on emoji card when we hover it like scaling the card size

_Originally posted by @KaifKhan7393 in https://github.com/aditya-singh9/kekfinder/issues/21#issuecomment-1260904902_

**Comment by aditya-singh9** [comment]
Just keep in mind that the scaling of the card does not affect the other cards.

If you want to work on this then let me know so that i assign it to you

**Comment by stubborn-1508** [comment]
I would like to work on this issue. Please assign it to me.
