### ISSUE TITLE
Search Bar enhancements

### ISSUE THREAD

**Issue by ArunBohra12** [aditya-singh9/kekfinder#24]
- Would it be nice to make the search input sticky?
**Reason -** When users search for an emoji and scroll to the bottom, they have to scroll up by clicking the button (in the light mode it seems that there is no back-to-top button)
- For UX, should we add a keyboard shortcut like `/` (similar to google or youtube) which focuses back on the search input?

**Comment by aditya-singh9** [comment]
Would you like to qork on this? @ArunBohra12

**Comment by SandeshGC** [comment]
Hey, I am new to open source and it's my first time in hacktoberfest. I would like to work on this issue.

**Comment by ArunBohra12** [comment]
> Would you like to work on this? @ArunBohra12

Sure, I would work on this. Please assign it to me

**Comment by ArunBohra12** [comment]
Hi,

I have done some work and made the search bar look like it does in the following images. Can you please check it and let me know your thoughts about it?

The `Press / to jump to search box` popup only appears when the user is not focused on the search and types something.

<img src="https://user-images.githubusercontent.com/94133102/193291196-31d03acc-983f-4194-9d5f-9e91b7189b3e.png" width="400" />
<img src="https://user-images.githubusercontent.com/94133102/193291367-edf9a3d3-56a9-4def-91a4-69474960ab2e.png" width="400" />

**Comment by aditya-singh9** [comment]
It looks really good.

**Comment by ArunBohra12** [comment]
> It looks really good. Have you created a pr?

Not yet.

**Comment by ArunBohra12** [comment]
#27 Created a pull request for this.

**Comment by Substancia** [comment]
Looks like the stickiness is looking weird...

<img width="582" alt="Screenshot 2022-10-02 at 22 11 29" src="https://user-images.githubusercontent.com/27500147/193465797-b6fca2b0-af93-4dec-81e6-bfe27bccbbe3.png">

**Comment by ArunBohra12** [comment]
Do you have any solution to that or is it looking really bad and we should remove that?

**Comment by Substancia** [comment]
Maybe just put a background layer to the sticky part and color the background similar to the page's background, left to right end?

**Comment by Substancia** [comment]
@ArunBohra12 are you working on this?

**Comment by ArunBohra12** [comment]
As of now no!
