### ISSUE TITLE
Show all emojis when nothing is searched

### ISSUE THREAD

**Issue by kunaaal13** [aditya-singh9/kekfinder#25]
Should we show all emojis available when no search is done?? That would be a great enhancement

**Comment by kunaaal13** [comment]
will it be included in hacktoberfest? i'll. surely love to work on this

**Comment by aditya-singh9** [comment]
Yes, i will put the hactoberfest-accepted tag

**Comment by kunaaal13** [comment]
Okay great I'll be working on this

**Comment by aditya-singh9** [comment]
Already working on this .
