### ISSUE TITLE
UI improvement for "emoji cards" in mobile shape

### ISSUE THREAD

**Issue by Nogueira-lucas** [aditya-singh9/kekfinder#31]
The screen UI on mobile shape this cards are not so accessible. My suggestion is to make those bigger for make screen more style and usual.

![KekFinder](https://user-images.githubusercontent.com/20306466/193392166-ab15214f-574c-4f5d-9027-9818c672277e.png)

**Comment by Nogueira-lucas** [comment]
may I work that issue?

**Comment by aditya-singh9** [comment]
Yep you can work on this
