### ISSUE TITLE
Contributions in readme 

### ISSUE THREAD

**Issue by YasirObaibullah99** [aditya-singh9/kekfinder#33]
I can add top Contributions to the website and project admin in the readme section

**Comment by YasirObaibullah99** [comment]
Hey I have added top contributors and project admin in readme So it's looking good or do I need to do any changes before PR
![Screenshot from 2022-10-02 00-37-54](https://user-images.githubusercontent.com/83706868/193424778-c1ffc23e-c421-45e9-b348-2f8f184b2dca.png)

**Comment by aditya-singh9** [comment]
Remove the projects admin thing

And keep thr contributor only and keep it at the end

You can think it yourself about where to keep it (not on top)

**Comment by YasirObaibullah99** [comment]
ya that contributor part will be at on Booton after License I think that will be good

**Comment by aditya-singh9** [comment]
Think accordingly and create a pr
