### ISSUE TITLE
**Hi, i have some idea's :**

### ISSUE THREAD

**Issue by aditya-singh9** [aditya-singh9/kekfinder#37]
**Hi, i have some idea's :**

1. Adding Shadow color (#ffc83d) same as the light theme toggle button :-
![image](https://user-images.githubusercontent.com/96531798/193384147-fa386823-b0f6-46be-b8c4-2e6c6ecf03fd.png)

2. changing the scroll-bar / scroll-bar thumb :-
  **Light- theme :**
![image](https://user-images.githubusercontent.com/96531798/193384316-32b05f51-9476-481d-99e4-5f410aa507b1.png)

  **Dark- theme :**
![image](https://user-images.githubusercontent.com/96531798/193384341-eb71ec45-cfc3-45cf-813c-12de6cf380d0.png)

### **And some more , which i am designing in figma and adobe xd, then testing in the code** 

_Originally posted by @Rudresh-pandey in https://github.com/aditya-singh9/kekfinder/issues/21#issuecomment-1264218678_

**Comment by Rudresh-pandey** [comment]
hello , you can assign it to me
