### ISSUE TITLE
Code restructuring

### ISSUE THREAD

**Issue by Substancia** [aditya-singh9/kekfinder#41]
The code files need to be restructured for better readability (especially in the future when more files are created). Basically different components (js files and their supporting files like css) need to go into a folder, so that the containers folder has only folders in it. This helps compartmentalise the code better.

**Comment by Substancia** [comment]
If you're creating new files, please put them in respective new folders INSIDE "components" folder from now on. And to make changes to existing files, please let me know when no one is doing critical work, to avoid merge conflicts and breaking changes.

cc:// @chiggshiggs @aditya-singh9  @YasirObaibullah99 @Nogueira-lucas @kunaaal13

**Comment by Rudresh-pandey** [comment]
**Hello** , @Substancia as you have mentioned about restructuring of the current code base which will improve the readability , I have worked upon it and made separate folders for each of the features and also changes the respective file locations (path) .
.
.
**You can assign this issue to me and i will make a PR** :)

**Comment by Rudresh-pandey** [comment]
We should update the contributing.md

**Comment by Rudresh-pandey** [comment]
**Should i make a PR of** :-

1.  Creating different folders which contains js and their respective css files
2.  Updating the contribution.md (adding necessary info about creating separate folders for each features made by the contributers)

**Comment by Substancia** [comment]
I had asked earlier about making this restructuring myself, had a chat with @aditya-singh9 , decided to wait till everyone's critical work are done to avoid merge conflicts for everyone.

I am very keen about this and would like to get on this (especially with my other issue closed I have bandwidth now to orchestrate with everyone individually), but I'll be good with whoever @aditya-singh9 assigns this to.

**Comment by Rudresh-pandey** [comment]
you can take this i am working on the UI part :)

**Comment by aditya-singh9** [comment]
I think i will assign it to @Substancia because he started this thread and thought of restructuring.

**Comment by Substancia** [comment]
Example of what I'd like to implement: https://github.com/Substancia/OneshotAI-MERN-client-webapp/

**Comment by Substancia** [comment]
@aditya-singh9 looks like coast is clear for this issue solving. Out of 4 currently active issues, 2 seem to be unaffected (as per their assignees), and 2 are mine with PRs up and ready to be merged. Once mine are merged, I can immediately get into this before someone starts another issue with critical work.

**Comment by YasirObaibullah99** [comment]
@Substancia Have to done #41 issue then please merge it

**Comment by Substancia** [comment]
@YasirObaibullah99 sorry, did you mean that I wait till you finish your work? If so, when are you expecting to raise you PR?

**Comment by YasirObaibullah99** [comment]
I have already raised the PR

**Comment by Substancia** [comment]
Cool, I'll wait till your PR is merged. Thanks.

**Comment by Substancia** [comment]
@aditya-singh9 [PR](https://github.com/aditya-singh9/kekfinder/pull/68) has been raised. Added couple comments in PR to describe the changes made.
