### ISSUE TITLE
Items selected textbox size and width

### ISSUE THREAD

**Issue by mohakgupt** [aditya-singh9/kekfinder#45]
When large number of emoji are selected the items selected box does not change its height and the excess emojis cut through the content below:
![image](https://user-images.githubusercontent.com/100181077/193426508-6392c91b-c28d-47d0-b3bf-0c3ef93960a9.png)
I would like to fix this under Hactoberfest 2022.

**Comment by aditya-singh9** [comment]
Okay, this will fix that bug.
I am aasigning it to you

**Comment by aditya-singh9** [comment]
Are you working on this?

**Comment by mohakgupt** [comment]
> Are you working on this?

Yes 🙂

**Comment by Substancia** [comment]
Hey @mohakgupt is this a critical work, and if I proceed with https://github.com/aditya-singh9/kekfinder/issues/41, will it be breaking changes to your work?

**Comment by mohakgupt** [comment]
> Hey @mohakgupt is this a critical work, and if I proceed with #41, will it be breaking changes to your work?

Let me finish

**Comment by mohakgupt** [comment]
https://user-images.githubusercontent.com/100181077/193451684-d767bfc2-29eb-4abc-abf0-52e050141540.mp4

How is this layout?

**Comment by aditya-singh9** [comment]
Bruh the new images of copy and delete made it look more ugly

Please let them be the way they were and make a pr about the original fix

**Comment by mohakgupt** [comment]
> Bruh the new images of copy and delete made it look more ugly
> 
> Please let them be the way they were and make a pr about the original fix

ok
