### ISSUE TITLE
[FEATURE] Open graph

### ISSUE THREAD

**Issue by Nakamcode** [aditya-singh9/kekfinder#47]
### The website is missing an image on the open graph
![captures_chrome-capture-2022-9-2](https://user-images.githubusercontent.com/89482825/193436990-673a44be-7a4e-4b83-aa6c-c3f8709287c9.png)

### An open graph is a preview image that shows when a link is shared on social media

**for more info about open graphs read the blog below**
https://ahrefs.com/blog/open-graph-meta-tags/

**Comment by aditya-singh9** [comment]
You can add that thing
I am assigning it to you

**Comment by Nakamcode** [comment]
sure, thanks
