### ISSUE TITLE
Add a backspace button on text field

### ISSUE THREAD

**Issue by akshay399** [aditya-singh9/kekfinder#51]
I would like to add a backspace button here so when the user clicks it, the textfield is cleared.

<img width="409" alt="image" src="https://user-images.githubusercontent.com/55823965/193441561-fbce18fb-4cf5-4ba1-bcce-4e0f19949984.png">

**Comment by aditya-singh9** [comment]
I do not think that there is a need of that, we have backspace buttton on our mobile keyboards and laptop keyboards.
