### ISSUE TITLE
Overflow of emoji's

### ISSUE THREAD

**Issue by deep-69bits** [aditya-singh9/kekfinder#53]
**BUG**
Overflow of emoji's as you see in video
**Reproduce**
Change in css to fix this bug 

<img src="https://user-images.githubusercontent.com/96793524/193446155-dd53c1b4-1e9e-490e-b873-a0abebc64e67.gif" width="700" height="400" />

**Comment by aditya-singh9** [comment]
https://github.com/aditya-singh9/kekfinder/issues/45
