### ISSUE TITLE
Clear search keyword button in search bar

### ISSUE THREAD

**Issue by Substancia** [aditya-singh9/kekfinder#54]
Just a wild suggestion, should we add a clear button in the search bar to clear the keywords typed in the search bar? Sure we can always use backspace or drag click all text and delete, but since the search bar has space for this (and I personally find this helpful when using one-handed), maybe we can contemplate having one? Open to discuss.

<img width="602" alt="Screenshot 2022-10-02 at 16 50 50" src="https://user-images.githubusercontent.com/27500147/193451696-cf098676-81a9-4e35-8b1b-42824bb941ec.png">
I'm thinking right end of the search bar.

**Comment by aditya-singh9** [comment]
Hmmm, okay you can take this up

Btw can you think something about the copy multiple emojis textbox

The textbox just looks odd.
I would like to discuss this in new issue.

**Comment by Substancia** [comment]
I'll think of something and let you know. Meanwhile if you're looking for more heads to brainstorm for this, we can open this issue rn as "improve emoji textbox UI" or something.

Will get back to you once I'm back home.

**Comment by Substancia** [comment]
@aditya-singh9 how does this look? https://github.com/Substancia/kekfinder/tree/feature/search-clear-button

**Comment by aditya-singh9** [comment]
Can you please send a screenshot or a video about the end results.

**Comment by Substancia** [comment]
<img width="605" alt="Screenshot 2022-10-03 at 00 40 03" src="https://user-images.githubusercontent.com/27500147/193471878-f8182697-d106-4f5e-88d0-ca7ccd6afab7.png">
<img width="650" alt="Screenshot 2022-10-03 at 00 40 15" src="https://user-images.githubusercontent.com/27500147/193471884-9a0b9c44-af3a-495d-9b66-47eaa9fcc7b0.png">
