### ISSUE TITLE
Empty suggestions list during first time access in a machine

### ISSUE THREAD

**Issue by Substancia** [aditya-singh9/kekfinder#60]
When the app is used for the very first time, and nothing is typed in search bar, no emojis are shown. Instead maybe we can show all emojis ONLY during the first time loading? We can keep the frequently used emojis suggestions during subsequent uses.

**Comment by aditya-singh9** [comment]
I am good with it

**Comment by Substancia** [comment]
Fixed. Raising a PR now.

<img width="950" alt="Screenshot 2022-10-03 at 14 36 25" src="https://user-images.githubusercontent.com/27500147/193540761-78dcbc78-9ef6-4c6b-b301-8d0b7df231ab.png">
<img width="901" alt="Screenshot 2022-10-03 at 14 36 43" src="https://user-images.githubusercontent.com/27500147/193540797-4aaa0fce-cc17-46cf-bb0d-fb47acc70c8f.png">
<img width="793" alt="Screenshot 2022-10-03 at 14 37 18" src="https://user-images.githubusercontent.com/27500147/193540820-95560843-b09b-46d1-9706-e295f45fb1d4.png">
