### ISSUE TITLE
Weird behaviour when deleting emojis after selecting (only specific emojis)

### ISSUE THREAD

**Issue by Substancia** [aditya-singh9/kekfinder#61]
Have a fire and star lined up
<img width="628" alt="Screenshot 2022-10-03 at 01 47 37" src="https://user-images.githubusercontent.com/27500147/193474596-55951997-5942-424d-87ba-63a149e6db30.png">

Hit delete one to remove star, and this happens
<img width="638" alt="Screenshot 2022-10-03 at 01 47 44" src="https://user-images.githubusercontent.com/27500147/193474601-e0fb1dcd-865e-4c82-8709-869eb83c1f09.png">

Hit delete again
<img width="659" alt="Screenshot 2022-10-03 at 01 47 52" src="https://user-images.githubusercontent.com/27500147/193474603-add9eb87-fd85-43cf-b260-0fb3ce215149.png">

This behaviour is consistently observed certain emojis, like whenever we star after fire in selected list.

**Comment by aditya-singh9** [comment]
I am not sure why it is happening
Can you try and solve

**Comment by Substancia** [comment]
I'll snoop around, and this looks like high priority too. So if we can have more testers testing this, we can describe the behaviour clearer, like why only few emojis cause this and which all. I'll take a look.

**Comment by Substancia** [comment]
Observation: This seems to happen only when we delete a star ⭐

<img width="630" alt="Screenshot 2022-10-03 at 13 54 30" src="https://user-images.githubusercontent.com/27500147/193534652-115f1674-a1e2-470f-9c1a-de7610c7e4de.png">
<img width="614" alt="Screenshot 2022-10-03 at 14 05 30" src="https://user-images.githubusercontent.com/27500147/193534686-a44aa92a-80c2-4d03-81fa-22e800414b18.png">

(Context for whoever ends up fixing this)

**Comment by Substancia** [comment]
Think I found the issue.
`ItemsSelected.js` has the delete function with line `    updateSelectedItems(selectedItems.substr(0, (selectedItems.length) - 2))`. I changed the 2 to 1, and following are the results as I click delete each time:-

<img width="658" alt="Screenshot 2022-10-03 at 15 28 31" src="https://user-images.githubusercontent.com/27500147/193551261-2868adc1-18cb-4dca-a704-17ada1fbf17f.png">
<img width="631" alt="Screenshot 2022-10-03 at 15 28 38" src="https://user-images.githubusercontent.com/27500147/193551287-95ee0511-ecd7-4878-a05a-1ce1fd38936c.png">
<img width="628" alt="Screenshot 2022-10-03 at 15 28 51" src="https://user-images.githubusercontent.com/27500147/193551307-6a0af9e0-6a8c-40b6-96a8-d2d52703ab14.png">
<img width="644" alt="Screenshot 2022-10-03 at 15 28 59" src="https://user-images.githubusercontent.com/27500147/193551335-f6c6028a-9fac-4c93-916d-235779742027.png">
<img width="599" alt="Screenshot 2022-10-03 at 15 29 05" src="https://user-images.githubusercontent.com/27500147/193551368-8caa0e83-8a50-4715-a2bd-b3ca14feb55b.png">
<img width="625" alt="Screenshot 2022-10-03 at 15 29 11" src="https://user-images.githubusercontent.com/27500147/193551393-dcfbd539-a763-46e8-b3ca-c22ebcb98dcc.png">
<img width="620" alt="Screenshot 2022-10-03 at 15 29 19" src="https://user-images.githubusercontent.com/27500147/193551407-0acc130d-818e-4616-af0e-e1be2f703a1f.png">

I suspect that different emojis are different characters long, like fire and water are 2 characters long each (I suspect that's why substring function is reducing 2 characters at a time), star is 1 character long.

If this is the case, a solution would be to restructure the function to have the selected emojis as an array of emojis instead of string of emojis (difference being using not "🔥🔥⭐" but ["🔥", "🔥", "⭐"]).

**Comment by aditya-singh9** [comment]
Cool, pls fix and make a pr

**Comment by Substancia** [comment]
Since the repo will be blocked the entire day, I'll take a day off and come back to this once the new UI is implemented, that cool? I already have the logic figured out, will raise a PR right after merging the new UI PR.

**Comment by aditya-singh9** [comment]
Cool

**Comment by Substancia** [comment]
[PR](https://github.com/aditya-singh9/kekfinder/pull/70) has been raised for this fix, purely functional fix, can wait till the UI PR is merged, will not cause merge conflicts.
