### ISSUE TITLE
Show Emoji Name on hover

### ISSUE THREAD

**Issue by soustab10** [aditya-singh9/kekfinder#69]
### Emoji Name must appear on card on hover.
![image](https://user-images.githubusercontent.com/95632583/193785052-1c5f2d43-a7b8-42a1-ab7e-0283df1bd013.png)

This is especially useful for flag emojis where the emojis look almost the same.
![image](https://user-images.githubusercontent.com/95632583/193785458-96aa17bc-e60b-4c33-ac8a-f597e7036fd5.png)

If approved, I would like to work on this issue.

**Comment by Substancia** [comment]
I like the idea, especially with the flag emojis and if people wanna reference a particular country but don't really know what their flag looks like. This could be a good addition.

But this enhancement does involve logic change beyond just adding a hover, like adding a new key to the emoji object entries, handling them in localstorage etc. If all these can be handled, all good. If this is being done, I can assist @soustab10 verifying if anything got missed.

**Comment by aditya-singh9** [comment]
If @soustab10 would like to work on @Substancia suggestions then i will assign it to @soustab10

**Comment by janmesh799** [comment]
can i work on this project @aditya-singh9

**Comment by aditya-singh9** [comment]
You can absolutely work on this project by adding new features or solving bugs.

But you should not work on this issue as this is originally created by @soustab10 and i will not assign it to anyonelese until he agrees to

You can open a new issue, describing the stuff you want to work on

**Comment by soustab10** [comment]
I am willing to work on this. Thank you.

**Comment by Substancia** [comment]
@soustab10 are you working on this?

**Comment by aditya-singh9** [comment]
It not responding in 5days you are off

**Comment by Substancia** [comment]
Tbh I don't think I have the patience or time to add a new field to every object in the JSON file, so I'm not actively taking responsibility for this. Since the issue opener @soustab10 is non-responding, it's up to you whether to keep this issue open for someone else, or closing as not planned.
